/* =========================================================
   V2 - FOREIGN KEYS e ÍNDICES
   ========================================================= */
ALTER TABLE APLICACAO
  ADD CONSTRAINT FK_APLICACAO_USUARIO
  FOREIGN KEY (ID_USUARIO)
  REFERENCES USUARIO(ID_USUARIO)
  ON DELETE CASCADE;

ALTER TABLE APLICACAO
  ADD CONSTRAINT FK_APLICACAO_CRIPT
  FOREIGN KEY (ID_CRIPT)
  REFERENCES CRIPTOMOEDA(ID_CRIPT)
  ON DELETE CASCADE;

CREATE INDEX IX_APLICACAO_USUARIO ON APLICACAO(ID_USUARIO);
CREATE INDEX IX_APLICACAO_CRIPT  ON APLICACAO(ID_CRIPT);
